name: Build Keycloak SPI

on:
  push:
    branches: [ main, master, develop ]
  pull_request:
    branches: [ main, master, develop ]
  workflow_dispatch:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'

    - name: Cache Maven dependencies
      uses: actions/cache@v4
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-m2

    - name: Build Keycloak SPI
      run: |
        mvn clean compile test package

    - name: List generated artifacts
      run: |
        ls -la target/

    - name: Upload JAR artifact
      uses: actions/upload-artifact@v4
      with:
        name: keycloak-internal-id-spi
        path: target/keycloak-internal-id-spi-*.jar
        retention-days: 30

    - name: Upload to release (if release event)
      if: github.event_name == 'release'
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: target/keycloak-internal-id-spi-1.0.0.jar
        asset_name: keycloak-internal-id-spi-1.0.0.jar
        asset_content_type: application/java-archive
